Добавил загрузку Offers
htmlacademy-react/189337-six-cities-13 pull request #8
Opened 2023-08-01 18:03 UTC by Technopriest90

2023-08-05 03:27 UTC, Maxfri requested changes

2023-08-05 03:27 UTC, Maxfri commented on src/components/card/card.tsx
> +  const handleAddToFavorite = (): void => {
Void можно не указывать

2023-08-05 03:27 UTC, Maxfri commented on src/components/group-card-list/group-card-list.tsx
> +export default function GroupCardList(): JSX.Element {
Дефолтный экспорт обычно снизу пишут, а обычный вначале

2023-08-05 03:27 UTC, Maxfri commented on src/components/header/header.tsx
> +  const handleLogout = (evt: MouseEvent) => {
Сокращай как event или e

2023-08-05 03:27 UTC, Maxfri commented on src/components/header/header.tsx
> +                          <span className="header__favorite-count">{ favorites.length }</span>
Лишние пробелы

2023-08-05 03:27 UTC, Maxfri commented on src/components/login-form/login-form.tsx
> +  const handleLogin = (evt: FormEvent<HTMLFormElement>): void => {
Тут тоже не сокращай так пожалуйста)

2023-08-05 03:27 UTC, Maxfri commented on src/components/login-form/login-form.tsx
> +      action="#"
Экшен и метод можно убрать

2023-08-05 03:27 UTC, Maxfri commented on src/components/review-form/review-form.tsx
>    const handleSubmitReview = ((evt: FormEvent<HTMLFormElement>) => {
Тут тоже, пожалуйста)

2023-08-05 03:27 UTC, Maxfri commented on src/components/review-form/review-form.tsx
> +    if(offerId) {
Пробел

2023-08-05 03:27 UTC, Maxfri commented on src/hooks/use-map.ts
> +    if (mapRef.current !== null) {
!mapRef.current можно

2023-08-05 03:27 UTC, Maxfri commented on src/index.tsx
> +      <ToastContainer />
Можно тостконтейнер в апп занести

2023-08-05 03:27 UTC, Maxfri commented on src/pages/offer/offer.tsx
> +  const offer = useAppSelector((state) => state.offer);
Офер можно ниже деструктуризовать

2023-08-05 03:27 UTC, Maxfri commented on src/services/token.ts
> +export const dropToken = (): void => {
removeToken

2023-08-05 03:27 UTC, Maxfri commented on src/store/api-action.ts
> +  async (_arg, { dispatch, extra: api }) => {
Можно везде в try catch обернуть

2023-08-05 03:27 UTC, Maxfri commented on src/store/reducer.ts
> +    const offer = state.offers.find(({ id }) => id === payload.id);
Лучше эти манипуляции из редюсера вынести

2023-08-07 14:07 UTC, Technopriest90 commented on src/components/group-card-list/group-card-list.tsx
> +export default function GroupCardList(): JSX.Element {
А у меня тут один экспорт) Что имеешь ввиду?

2023-08-07 14:16 UTC, Technopriest90 commented on src/hooks/use-map.ts
> +    if (mapRef.current !== null) {
не получится, т к Map от Leaflet ругается на null

2023-08-07 14:20 UTC, Technopriest90 commented on src/pages/offer/offer.tsx
> +  const offer = useAppSelector((state) => state.offer);
offer может быть null, как предлагаешь деструктурировать?

2023-08-07 14:23 UTC, Technopriest90 commented on src/store/api-action.ts
> +  async (_arg, { dispatch, extra: api }) => {
в services/api.ts уже есть обработка ошибок

` api.interceptors.response.use(
    (response) => {
      store.dispatch(setLoading(false));
      return response;
    },
    (error: AxiosError<DetailMessageType>) => {
      if (error.response && shouldDisplayError(error.response)) {
        const detailMessage = (error.response.data);

        toast.error(detailMessage.message, {
          position: TOAST_POSITION
        });
      }
      store.dispatch(setLoading(false));
      throw error;
    }
  );`

2023-08-08 09:22 UTC, merged